name: multimodal-rag-pdf
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.12
  - pip>=23.0
  - numpy>=1.24.0
  - pandas>=1.5.0
  - pillow>=9.0.0
  - opencv>=4.8.0
  - jupyter>=1.0.0
  - notebook>=6.5.0
  
  # Tesseract OCR (required for PDF processing based on project memory)
  - tesseract>=5.0.0
  
  # pip dependencies
  - pip:
    - langchain-core>=0.1.0
    - langchain-community>=0.0.1
    - langchain-unstructured>=0.1.0
    - unstructured>=0.10.0
    - unstructured[local-inference]>=0.10.0
    - pypdf>=3.0.0
    - pytesseract>=0.3.10
    - paddlepaddle>=2.5.0
    - paddleocr>=2.7.0
    - reportlab>=3.6.0
    - python-dotenv>=1.0.0